version: '3'
services:
  db-customer:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 2512
      MYSQL_DATABASE: ecommerce_customers
    ports:
      - "3307:3306"

  db-items:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: ecommerce_items
    ports:
      - "27017:27017"

  db-transactions:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 2512
      POSTGRES_DB: ecommerce_transactions
    ports:
      - "5432:5432"

  customer:
    build: ./customer_service
    ports:
      - "8001:8001"
    depends_on:
      - db-customer

  items:
    build: ./items_service
    ports:
      - "8005:8005"
    depends_on:
      - db-items

  cart:
    build: ./cart_service
    ports:
      - "8002:8002"
    depends_on:
      - db-transactions

  order:
    build: ./order_service
    ports:
      - "8003:8003"
    depends_on:
      - db-transactions

  paying:
    build: ./paying_service
    ports:
      - "8004:8004"
    depends_on:
      - db-transactions

  shipping:
    build: ./shipping_service
    ports:
      - "8006:8006"
    depends_on:
      - db-transactions

  gateway:
    build: ./gateway_service
    ports:
      - "8000:8000"
    depends_on:
      - customer
      - items
      - cart
      - order
      - paying
      - shipping